services:
  api:
    build: .
    container_name: diabetes_api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000
    extra_hosts:
        - "host.docker.internal:host-gateway"
    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: monitoring
